default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: t_clone_development
test:
  <<: *default
  database: t_clone_test
production:
  <<: *default
  database: t_clone_production
  username: t_clone
  password: <%= ENV['T_CLONE_DATABASE_PASSWORD'] %>
